"""Generate a Structurizr DSL workspace containing only project-level components."""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from analysis.graph import build_relation_graph
from model.project import Project


def _dsl_string(value: Any) -> str:
    """Escape text for a quoted Structurizr DSL string."""
    text = str(value or "")
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return re.sub(r"[\r\n\t]+", " ", text).strip()


def _identifier(value: str, used: set[str]) -> str:
    base = re.sub(r"[^A-Za-z0-9_]", "_", value).strip("_") or "component"
    if base[0].isdigit():
        base = "component_" + base
    candidate = base
    index = 2
    while candidate in used or candidate in {"project", "views", "styles"}:
        candidate = f"{base}_{index}"
        index += 1
    used.add(candidate)
    return candidate


def build_structurizr_dsl(project: Project) -> str:
    """Build a C4 container view from the collapsed project component graph.

    The DSL intentionally contains no files, classes, functions, or methods.
    Each node is a top-level project component and each edge is an aggregated
    component-to-component dependency.
    """
    graph = build_relation_graph(project, view="project_overview", max_nodes=None, max_edges=None)
    project_name = _dsl_string(project.name or "Software Project") or "Software Project"
    project_id = "project"
    node_ids: dict[str, str] = {}
    used: set[str] = {project_id}
    lines = [
        f'workspace "{project_name} Architecture" "Project-level architecture generated by Barkly Docs." {{',
        "    model {",
        f'        {project_id} = softwareSystem "{project_name}" "System analyzed by Barkly Docs." {{',
    ]
    for node in graph.nodes:
        node_id = _identifier(node.label, used)
        node_ids[node.id] = node_id
        file_count = int(node.metadata.get("file_count", 0) or 0)
        entity_count = int(node.metadata.get("entity_count", 0) or 0)
        description = f"Top-level project area. {file_count} source file(s); {entity_count} indexed code element(s)."
        lines.append(
            f'            {node_id} = container "{_dsl_string(node.label)}" "{_dsl_string(description)}" "Software"'
        )
    lines.append("        }")

    for edge in graph.edges:
        source_id = node_ids.get(edge.source)
        target_id = node_ids.get(edge.target)
        if not source_id or not target_id:
            continue
        count = int(edge.metadata.get("relationship_count", 1) or 1)
        kinds = ", ".join(str(kind) for kind in edge.metadata.get("relationship_kinds", []))
        label = f"connects to ({count})"
        if kinds:
            label += f" — {kinds}"
        lines.append(
            f'        {project_id}.{source_id} -> {project_id}.{target_id} "{_dsl_string(label)}"'
        )

    lines.extend([
        "    }",
        "    views {",
        f'        container {project_id} "project-overview" "Project-level component dependencies" {{',
        "            include *",
        "            autolayout lr",
        "        }",
        "        styles {",
        '            element "Software System" { background #171117 color #FFD5E6 stroke #FF6B9D }',
        '            element "Container" { shape RoundedBox background #2A1B27 color #FFD5E6 stroke #FF6B9D }',
        '            relationship { color #7DFFB2 routing Orthogonal }',
        "        }",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def write_structurizr_files(project: Project, output_dir: str | Path) -> list[Path]:
    """Write the project graph, a static-site Dockerfile, and a ready-to-run Compose stack.

    The generated site is served by nginx on host port 8000 by default. Structurizr
    Lite uses host port 8080. Both are configurable through environment variables,
    and the two services use separate container ports so their listeners do not
    collide.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    architecture_dir = output_path / "architecture"
    architecture_dir.mkdir(parents=True, exist_ok=True)
    dsl_path = architecture_dir / "workspace.dsl"
    compose_path = architecture_dir / "docker-compose.yml"
    dockerfile_path = output_path / "Dockerfile"

    dsl_path.write_text(build_structurizr_dsl(project), encoding="utf-8")
    dockerfile_path.write_text(
        "# Generated by Barkly Docs. Serves the static documentation site.\n"
        "FROM nginx:alpine\n"
        "COPY . /usr/share/nginx/html/\n"
        "EXPOSE 80\n",
        encoding="utf-8",
    )
    compose_path.write_text(
        "services:\n"
        "  structurizr-lite:\n"
        "    image: structurizr/lite:latest\n"
        "    ports:\n"
        '      - "${STRUCTURIZR_PORT:-8080}:8080"\n'
        "    volumes:\n"
        "      - ./workspace.dsl:/usr/local/structurizr/workspace.dsl:ro\n"
        "    restart: unless-stopped\n"
        "  barkly-docs-site:\n"
        "    build:\n"
        "      context: ..\n"
        "      dockerfile: Dockerfile\n"
        "    ports:\n"
        '      - "${BARKLY_DOCS_PORT:-8000}:80"\n'
        "    restart: unless-stopped\n",
        encoding="utf-8",
    )
    return [dsl_path, compose_path, dockerfile_path]


__all__ = ["build_structurizr_dsl", "write_structurizr_files"]
